# Generated by Django 3.2.4 on 2021-06-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerName', models.CharField(max_length=30)),
                ('sellerNumber', models.IntegerField()),
                ('carMaker', models.CharField(max_length=30)),
                ('carModel', models.CharField(max_length=30)),
                ('carYear', models.DateField()),
                ('carCondition', models.CharField(max_length=10)),
                ('carPrice', models.IntegerField()),
            ],
        ),
    ]
