# Generated by Django 3.2.4 on 2021-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDearlership', '0002_alter_car_caryear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carCondition',
            field=models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=10),
        ),
    ]
