# Generated by Django 3.2.4 on 2021-06-25 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carDearlership', '0004_alter_car_sellernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carPrice',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
