# Generated by Django 3.2.4 on 2021-06-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carDearlership', '0005_alter_car_carprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carMaker',
            new_name='carMake',
        ),
    ]
