# Generated by Django 3.2.4 on 2021-06-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carDearlership', '0007_auto_20210625_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerName', models.CharField(max_length=30, verbose_name="Buyer's Name")),
                ('buyerInfo', models.CharField(max_length=30, verbose_name='Buyer`s Contact Number')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDearlership.car')),
            ],
        ),
    ]
